name: url_shortener
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  pretty_qr_code: ^3.1.0
  bot_toast: ^4.1.3
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf


